# Generated by Django 5.1.6 on 2025-03-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos_Main_App', '0005_rename_username_contactsupport_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsupport',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='contactsupport',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
