# Generated by Django 5.1.6 on 2025-03-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos_Main_App', '0006_contactsupport_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsupport',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
