# Generated by Django 5.1.6 on 2025-03-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos_Main_App', '0009_alter_contactsupport_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsupport',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
