name: Deploy Backend

on:
  push:
    paths:
      - 'pos-backend/**'   # Runs only when files inside "pos-backend" are changed
    branches:
      - new_staging_test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          cd pos-backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pos-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pos-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/pos-app
            docker-compose down  # Stop running containers
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pos-backend:latest
            docker-compose up -d  # Restart services
            docker system prune -f  # Clean up unused images
